apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- onepassword.yaml
- deployment.yaml
- ingress-route.yaml
- service.yaml
namespace: default
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: vigo-auth-organisation-selector
    app.kubernetes.io/managed-by: ga
    app.kubernetes.io/name: vigo-auth-organisation-selector
    app.kubernetes.io/part-of: common
    app.kubernetes.io/version: latest
    fintlabs.no/team: flais
